export enum InteractionMode {
  NONE = 'NONE',
  DRAGGING = 'DRAGGING',
  RESIZING_TOP = 'RESIZING_TOP',
  RESIZING_BOTTOM = 'RESIZING_BOTTOM',
  RESIZING_LEFT = 'RESIZING_LEFT',
  RESIZING_RIGHT = 'RESIZING_RIGHT',
  CREATING = 'CREATING',
}